/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import sample_sub_project.Library;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var lib = new Library();
        lib.someLibraryMethod();
    }
}
